### ISSUE TITLE
*が3つの時に<em><strong>xxxx</strong></em>とならない。

### ISSUE THREAD

**Issue by kmtomo** [peaceroad/p7d-markdown-it-strong-ja#1]
素晴らしいプラグインありがとうございます。
markdown-itの＊で囲ったときに起こる問題をピタッと直してくれました。

しかし一つだけ問題が発生しました。
`***xxxx***`と*が3つの時に、通常ですと`<em><strong>xxxx</strong></em>`となるのですが、`<strong>*xxxx</strong>*`となってしまいます。

4つ、5つ、6つと数が増えると従来の挙動になってくれるので問題はございません。
3つの時だけ正常ではない形になってしまいます。
```
<em> -> <strong> -> <em><strong>（ここだけおかしい） -> <strong><strong> -> <em><strong><strong> -> <strong><strong><strong> -> <em><strong><strong><strong> -> <strong> x 4 -> <em><strong> x 4 -> <strong> x 5 -> ...
```
となっていくのが従来の変換だと思います。

可能でしたらどうかご対処頂けますと行幸です。

このような素晴らしいプラグインを作成して頂き誠にありがとうございます。

**Comment by peaceroad** [comment]
ご指摘ありがとうございます。
気づいていたのですが、もともと荒い動作なのと、そのようなケースがなかったので放置していました。
issueをいただいた頃、二重ループを外したくて作り直すついでに、`***`の件にも対応してみました。
ラフには上手く動くかと思います。これでcloseしておきます。

なおcommonmarkのspec的には、「」で囲ったときや句読点の外側にアスタリスクがあっても処理されるように問題が整理されているようです。
https://github.com/commonmark/commonmark-spec/issues/650
そのため、そのうちcommnmakで、ゆくゆくはmarkdown-it等でもふつうに処理されるようになるかと思います。

**Comment by kmtomo** [comment]
お早い対応、誠にありがとうございます！
難解な問題にも見事に正確に展開されて動作しました。素晴らしいです。

ところが残念なことに、あるmarkdown文章を変換しようとしたところ、markdown-it自体が落ちるレベルの大きなエラーが発生するようになりました。

落ちたときは長大な文章でしたが、削って削って最小にすると以下のような文字でエラー落ちしました。
```
***と*が*
```
この文字列を入れると以下のようなエラーを吐き出してmd.renderが落ちます。
```
md.render.js:572 TypeError: Cannot read properties of undefined (reading 's')
    at checkNest (index.js:414:1)
    at setEm (index.js:340:1)
    at createMarks (index.js:438:1)
    at strongJa (index.js:511:1)
    at Array.<anonymous> (index.js:544:1)
    at __webpack_modules__../node_modules/markdown-it/lib/parser_inline.mjs.ParserInline.tokenize (parser_inline.mjs:156:1)
    at __webpack_modules__../node_modules/markdown-it/lib/parser_inline.mjs.ParserInline.parse (parser_inline.mjs:185:1)
    at Array.inline (inline.mjs:8:1)
    at __webpack_modules__../node_modules/markdown-it/lib/parser_core.mjs.Core.process (parser_core.mjs:56:1)
    at __webpack_modules__../node_modules/markdown-it/lib/index.mjs.MarkdownIt.parse (index.mjs:511:1)
```

もし可能でしたらご対処いただけますと僥倖です。

お忙しい中、ご対応いただき誠にありがとうございます。

**Comment by peaceroad** [comment]
早速試していただき、ありがとうございます。
`<em><strong>`や`<em><em>`となるときのネスト判断が良くなかったですね。修正したつもりです。
ではでは。

**Comment by kmtomo** [comment]
昨日の今日で即対応、ありがとうございます！

何故そのように荒ぶるのかってくらい強調入れてみましたが、見事にエラーが発生しなくなりました。
おかげで強調表示が安定して機能してくれるようになりました。

この度はお忙しい中、誠にありがとうございました。
